### ISSUE TITLE
Unit test fails when run with Emacs 25

### ISSUE THREAD

**Issue by phst** [snarfed/fillcode#3]
When running the unit tests with a build from the current `emacs-25` branch, a single test fails:

```none
.................F
fillcode-test.el:477:Comparison failure:templates: (in java-mode) expected:<"template <class A> qwert< A >;
bar;"> but was:<#("template <class A> qwert<A>;
bar;" 9 10 (category c-<-as-paren-syntax) 17 18 (category c->-as-paren-syntax) 24 25 (category c-<-as-paren-syntax) 26 27 (category c->-as-paren-syntax))>
.........

FAILURE!!!
Tests run: 26, Failures: 1, Errors: 0
```

**Comment by snarfed** [comment]
thanks for filling both of these issues! I'd definitely like to see them both fixed. any interest in sending a pull request or two?

**Comment by phst** [comment]
Will do. However, first I'll send a PR to add a LICENSE file.

**Comment by snarfed** [comment]
thanks! there's actually a license declaration in the README, so i don't feel the need for a separate LICENSE file. let need know if you have a specific reason to need it.
