### ISSUE TITLE
Assignment to free variables during byte-compile

### ISSUE THREAD

**Issue by gergelypolonkai** [snarfed/fillcode#9]
When installing from MELPA, the package gets byte compiled. During the process I get the following warnings:

```
Warning (bytecomp): assignment to free variable ‘fillcode-wrapped-fill-function’
Warning (bytecomp): reference to free variable ‘fillcode-wrapped-fill-function’
```

I know it’s pretty harmless, but given that it gives me an extra window (`*Compile-Log*`) at Emacs startup, it’s a bit annoying.

**Comment by snarfed** [comment]
thanks for filing @gergelypolonkai, eand thanks for using fillcode! i've fixed this in the repo here. feel free to try it!

**Comment by phst** [comment]
In addition I get the following undefined symbols: variable `c-mode-syntax-table`, functions `c-beginning-of-statement`, `python-nav-beginning-of-statement`, `c-end-of-statement`. You could either forward-declare them as well or require (at least at compile time) the features `cc-mode`, `cc-cmds`, and `python`.

**Comment by phst** [comment]
Also `python.el` doesn't actually define `py-indent-offset`, but `python-indent-offset`.

**Comment by gergelypolonkai** [comment]
@phst I don’t think it’s the responsibility of `fillcode` to define these. `c-*` symbols should be defined by `c-mode`, `python-*` should be defined by `python-mode`, etc.

**Comment by phst** [comment]
Yes, my PR requires these libraries so that the symbols are defined.

**Comment by gergelypolonkai** [comment]
Turns out this didn’t solve the actual issue; I still get the same warning about `fillcode-wrapped-fill-function`.

**Comment by gergelypolonkai** [comment]
…which is strange, because the code Emacs downloads from MELPA contains the corresponding `defvar` call.
